---
Name: approutes
After:
  - '#rootroutes'
  - '#coreroutes'
  - '#adminroutes'
---
SilverStripe\Control\Director:
  rules:
    'api/v1//$Action/$ID/$Name': TrinsicLabs\App\Controllers\ApiV1Controller
    'graphql': '%$SilverStripe\GraphQL\Controller.default'
    '$Model/$ID/$Action': TrinsicLabs\App\Controllers\AppController
    '': TrinsicLabs\App\Controllers\AppController
