---
Name: approutes
After:
  - '#rootroutes'
  - '#coreroutes'
  - '#adminroutes'
---
SilverStripe\Control\Director:
  rules:
    'graphql': '%$SilverStripe\GraphQL\Controller.default'
    '$Model/$ID/$Action': TrinsicLabs\App\Controllers\AppController
    '': TrinsicLabs\App\Controllers\AppController
