version: '3.3'

networks:
  network_divvy:
    external: true

services:
  web.app.divvy.com:
    image: php:7.3.6-apache
    container_name: web.app.divvy.com
    build:
      context: ./php-apache
    environment:
      APACHE_RUN_USER: '#1000'
      XDEBUG_CONFIG: remote_autostart=On remote_enable=On remote_host=host.docker.internal
    ports:
      - 80:80
    volumes:
      - ./server/:/var/www/html
      - ../host_queue:/var/www/html/host_queue
    networks:
      - network_divvy

  db.app.divvy.com:
    image: mysql:5.7.29
    container_name: db.app.divvy.com
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'app'
    volumes:
      - ./database/:/var/lib/mysql
    networks:
        - network_divvy

  mail.app.divvy.com:
    image: schickling/mailcatcher
    container_name: mail.app.divvy.com
    ports:
      - 1080:1080
    networks:
      - network_divvy
