<?php

use SilverStripe\Core\Environment;

$envMap = [
    'SS_DATABASE_CLASS' => 'SS_DATABASE_CLASS',
    'SS_DATABASE_SERVER' => 'RDS_HOSTNAME',
    'SS_DATABASE_PORT' => 'RDS_PORT',
    'SS_DATABASE_NAME' => 'RDS_DB_NAME',
    'SS_DATABASE_USERNAME' => 'RDS_USERNAME',
    'SS_DATABASE_PASSWORD' => 'RDS_PASSWORD',
    'SS_DATABASE_TIMEZONE' => 'SS_DATABASE_TIMEZONE',
    'SS_DATABASE_SCHEMA' => 'SS_DATABASE_SCHEMA',
    'SS_DATABASE_MEMORY' => 'SS_DATABASE_MEMORY',

    'SS_DEFAULT_ADMIN_USERNAME' => 'SS_DEFAULT_ADMIN_USERNAME',
    'SS_DEFAULT_ADMIN_PASSWORD' => 'SS_DEFAULT_ADMIN_PASSWORD',

    'SS_ENVIRONMENT_TYPE' => 'SS_ENVIRONMENT_TYPE',

    'SS_IGNORE_DOT_ENV' => 'SS_IGNORE_DOT_ENV',

    'SS_BASE_URL' => 'SS_BASE_URL',

    'SS_SEND_ALL_EMAILS_FROM' => 'SS_SEND_ALL_EMAILS_FROM',

    'SES_HOST' => 'SES_HOST',
    'SES_USERNAME' => 'SES_USERNAME',
    'SES_PASSWORD' => 'SES_PASSWORD',

    'TL_DEMO_ACCOUNT_USERNAME' => 'TL_DEMO_ACCOUNT_USERNAME',
    'TL_DEMO_ACCOUNT_PASSWORD' => 'TL_DEMO_ACCOUNT_PASSWORD',
];

foreach ($envMap as $ssKey => $envKey) {
    $value = getenv($envKey);

    if ($value) {
        Environment::setEnv($ssKey, $value);
    }
}
